name: "ociregistry: tag"

on:
  push:
    branches:
      - main
    paths:
      - "ociregistry/**"
      - ".github/workflows/ociregistry-tag.yml"

permissions:
  contents: write

jobs:
  tag:
    name: Bump version and tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 0.0.0
          TAG_PREFIX: ociregistry/v
          MAJOR_STRING_TOKEN: (MAJOR)
          MINOR_STRING_TOKEN: (MINOR)
          BRANCH_HISTORY: compare
