name: "ociregistry: test"

on:
  pull_request:
    paths:
      - "ociregistry/**"
      - ".github/workflows/ociregistry-test.yml"

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ociregistry
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ociregistry/go.mod
          cache-dependency-path: ociregistry/go.sum

      - name: Run tests
        run: go test -race -count=1 ./...
